# Default values for methode-article-image-set-mapper.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
  hasHealthcheck: "true"
replicaCount: 2
image:
  repository: coco/methode-article-image-set-mapper
  pullPolicy: IfNotPresent
resources:
  requests:
    memory: 128Mi
  limits:
    memory: 384Mi
env:
  Q_GROUP: ""
  Q_READ_TOPIC: ""
  Q_WRITE_TOPIC: ""
